apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quake
  annotations:
    custom-hostname: quake.toska # staging.toska.dev
spec:
  template:
    spec:
      containers:
        - image: treyyoder/quakejs
          env:
            - name: SERVER
              value: "quake.toska.dev"
            - name: HTTP_PORT
              value: "8080"
          ports:
          - containerPort: 80



# docker run -d --name quakejs -e SERVER=10.0.0.2 -e HTTP_PORT=8080 -p 8080:80 -p 27960:27960 treyyoder/quakejs:latest
