apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quake
  annotations:
    custom-hostname: quake.toska # staging.toska.dev
spec:
  template:
    spec:
      containers:
        - command:
          - q3
          - server
          - --config=/config/config.yaml
          - --content-server=http:/quake-content-svc
          - --agree-eula
          image: docker.io/criticalstack/quake:latest
          name: server
          volumeMounts:
            - name: quake3-server-config
              mountPath: /config
      volumes:
        - name: quake3-server-config
          configMap:
            name: quake3-server-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quake-content
spec:
  selector:
    matchLabels:
      run: quake-content
  replicas: 1
  template:
    metadata:
      labels:
        run: quake-content
    spec:
      containers:
      - command:
        - q3
        - content
        - --seed-content-url=http://content.quakejs.com
        image: docker.io/criticalstack/quake:latest
        name: content-server
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: quake3-content
          mountPath: /assets
      volumes:
        - name: quake3-content
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: quake-content-svc
spec:
  type: NodePort
  selector:
    run: quake-content-svc
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30002
      name: content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quake3-server-config
data:
  config.yaml: |
    fragLimit: 25
    timeLimit: 15m
    bot:
      minPlayers: 3
    game:
      motd: "Welcome to Critical Stack"
      type: FreeForAll
      forceRespawn: false
      inactivity: 10m
      quadFactor: 3
      weaponRespawn: 3
    server:
      hostname: "quakekube"
      maxClients: 12
      password: "changeme"
    commands:
      - addbot sarge 2
    maps:
    - name: q3dm7
      type: FreeForAll
      timeLimit: 10m
    - name: q3dm17
      type: FreeForAll
    - name: q3wctf1
      type: CaptureTheFlag
      captureLimit: 8
    - name: q3tourney2
      type: Tournament
    - name: q3wctf3
      type: CaptureTheFlag
      captureLimit: 8
    - name: ztn3tourney1
      type: Tournament