fragLimit: 10
timeLimit: 10m
game:
  motd: "Welcome to mluukkai simulator"
  type: FreeForAll
  forceRespawn: false
  inactivity: 20m
  quadFactor: 3
  weaponRespawn: 3
server:
  maxClients: 12
bot:	
  minPlayers: 2
maps:
- name: q3dm7
  type: FreeForAll
  timeLimit: 10m
- name: q3dm17
  type: FreeForAll
  timeLimit: 10m
- name: q3dm1
  type: FreeForAll
  timeLimit: 10m
#- name: q3dm14 Does not work
#- name: q3dm12 Does not work
- name: q3dm6
  type: FreeForAll
  timeLimit: 10m
- name: q3dm11
  type: FreeForAll
  timeLimit: 10m
- name: q3dm19
  type: FreeForAll
  timeLimit: 10m
