fragLimit: 15
timeLimit: 10m
cheats: 1
sv_cheats: 1
game:
  motd: "Welcome to mluukkai simulator"
  type: FreeForAll
  forceRespawn: false
  inactivity: 20m
  quadFactor: 3
  weaponRespawn: 3
commands:
  - sv_cheats 1
server:
  maxClients: 12
maps:
- name: q3dm1
  type: FreeForAll
  timeLimit: 15m
- name: q3dm14
  type: FreeForAll
  timeLimit: 15m
- name: q3dm12
  type: FreeForAll
  timeLimit: 15m
- name: q3dm17
  type: FreeForAll
  timeLimit: 1m
- name: q3dm6
  type: FreeForAll
  timeLimit: 15m
- name: q3dm11
  type: FreeForAll
  timeLimit: 15m
- name: q3dm19
  type: FreeForAll
  timeLimit: 15m
- name: q3dm7
  type: FreeForAll
  timeLimit: 15m
