apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/knative-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: quake3-server-config
    files: 
      - config.yaml
    