name: Deploy toska.dev

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-root.yaml'
      - 'root/**'
  workflow_dispatch:
    

defaults:
  run:
    working-directory: root

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./root
          file: ./root/Dockerfile
          tags: toska/toska-dev:${{ github.sha }}

      - uses: Azure/setup-kubectl@v1

      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      
      - name: Deploy
        run: |-
          ./kustomize edit set image IMAGE_FROM_KUSTOMIZATION=toska/toska-dev:${{ github.sha }}
          kubectl apply -k .
