name: Deploy toska.dev

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-root.yaml'
      - 'root/**'
  workflow_dispatch:
    

defaults:
  run:
    working-directory: root

jobs:
  setup-build-publish:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./root
          file: ./root/Dockerfile
          tags: toska/toska-dev:${{ github.sha }}
